# Generated by Django 4.2 on 2023-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('item_discount', models.FloatField()),
                ('item_desc', models.TextField()),
                ('item_image', models.CharField(max_length=500)),
                ('item_category', models.CharField(max_length=100)),
            ],
        ),
    ]
